.\" Manpage for client.
.\" Contact johnas@ualberta.ca to correct errors or typos.
.TH client 1 "31 March 2020" "1.0" "client man page"
.SH NAME
client
.SH SYNOPSIS
client [PORT NUMBER] [IP ADDRESS]
.SH ARGUMENTS
client takes two arguments:
    Argument 1: port number (Within 5000 and 64000)
    Argument 2: IP Address
.SH DESCRIPTION
client is a program sending transaction tasks to the server it is connected to.
.SH SEE ALSO
server(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Johnas Wong (CCID: johnas, ID: 1529241)